import "./globals.css";

import type { Metadata } from "next";
import { AppLayout } from '@/components/sidebar/AppLayout';
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Geist, Geist_Mono, Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "InfoRadio Web - Gestão Comercial e Financeira",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR" className={inter.variable} suppressHydrationWarning >
      <body
        className={`${geistSans.variable} ${geistMono.variable}
          min-h-screen bg-background font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppLayout>{children}</AppLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
